In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
a = np.ones((4,4))

In [6]:
print(a)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
a.shape

(4L, 4L)

In [10]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
x = x *2

In [56]:
m = np.array([[1,2,3],[4,5,6],[5,9,8],[4,1,2]])


In [40]:
m = m * .5

In [46]:
y = np.arange?


In [ ]:
y = np.arange

In [57]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [5, 9, 8],
       [4, 1, 2]])

In [68]:
m[:,0] + 10

array([11, 14, 15, 14])