In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


In [4]:
import json

input_ls = []
f = open('inputTraining.txt')

for line in iter(f):
    try:
        input_ls.append(json.loads(line))
    except ValueError:
        print line +'is not a proper json line'
f.close()

nCount = input_ls[0]
input_ls = input_ls[1:]

if len(input_ls) != nCount :
    print 'Data is not correct, pls check!'

    
calvin = []
hobbes = []
for c in input_ls:
    calvin.append(c.get('calvin'))
    hobbes.append(c.get('hobbes'))
    
target = []
f = open('outputTraining.txt')
for line in iter(f):
    line = line.replace('\n','')
    target.append(line)
f.close()
print len(target)

 is not a proper json line
15015


In [2]:
tot = []
for j in range(len(calvin)):
    comb = calvin[j] + " "+ hobbes[j]
    tot.append(comb)
    

NameError: name 'calvin' is not defined

In [126]:
target[0]


'electronics'

In [6]:
from sklearn import svm

In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import PassiveAggressiveClassifier



In [1]:
tot

NameError: name 'tot' is not defined

In [154]:
#clf = PassiveAggressiveClassifier(max_iter=10000, random_state=0,tol=1e-3)

In [7]:
clf = svm.SVC(C = 10, gamma=.001)

In [8]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
vectorizer = CountVectorizer()
vectorizer.fit(tot)
vectorizer.vocabulary_

x = vectorizer.transform(tot).toarray()
pca = PCA(n_components=50).fit_transform(x)

In [9]:
pca.shape

(15015L, 50L)

In [11]:
y = target

x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.30)
print(x.shape, x_train.shape, x_test.shape)


((15015L, 27679L), (10510L, 27679L), (4505L, 27679L))


In [ ]:
clf.fit(x_train,y_train)

In [182]:
from sklearn import metrics
y_pred = clf.predict(x_test)
print(metrics.confusion_matrix(y_pred,y_test))



[[ 78  70  82  95  52  71  56 111  85  68]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 27  40  34  30  22  33  20  34  28  37]
 [249 238 224 303 137 173  99 192 239 211]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [113 120 123 112  80 146 370 112  81 110]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]


ImportError: No module named jira

In [183]:
print(metrics.classification_report(y_pred,y_test))

              precision    recall  f1-score   support

     android       0.17      0.10      0.13       768
       apple       0.00      0.00      0.00         0
 electronics       0.07      0.11      0.09       305
         gis       0.56      0.15      0.23      2065
 mathematica       0.00      0.00      0.00         0
       photo       0.00      0.00      0.00         0
       scifi       0.68      0.27      0.39      1367
    security       0.00      0.00      0.00         0
        unix       0.00      0.00      0.00         0
   wordpress       0.00      0.00      0.00         0

   micro avg       0.17      0.17      0.17      4505
   macro avg       0.15      0.06      0.08      4505
weighted avg       0.50      0.17      0.25      4505



Learn Linear Algebra , and Probability theory, statsitics
Gilbert strand linear algebra - best available video lectures.


singular value decompositions
matrix factorizations

watch pycon and scipy videos on youtube

------------------------------------------------------------------------------------------

neuralnetworksanddeeplearning.com--
deeplearningbook.org

---------
follow OpenAI

